# Site settings
title: Breazu Laura's Homepage
description: This is my GitHub Pages site!
author: Breazu Laura
baseurl: "" # Leave this empty if deploying to the root of the domain
url: "https://username.github.io" # Replace with your GitHub Pages URL

# Theme settings
theme: jekyll-theme-leap-day

# Build settings
markdown: kramdown

