# Site settings
title: Breazu Laura's GitHub Pages Site
description: >- 
  Welcome to my GitHub Pages site! Here you'll find blog posts, projects, and more.
  This description will show up in search engine results.
author: John Doe
email: john@example.com
baseurl: "" # the subpath of your site, e.g., /blog
url: "https://username.github.io" # the base URL of your site (replace with your GitHub Pages URL)

# Build settings
markdown: kramdown
theme: minima # You can change this to other GitHub Pages supported themes

# Jekyll Plugins (optional)
plugins:
  - jekyll-feed    # Provides an RSS feed
  - jekyll-seo-tag # Improves SEO

# Navigation Links
# If you're using a theme that supports navigation, you can add links here
nav_links:
  home: /
  about: /about/
  blog: /blog/

# Exclude these files/folders from the build process
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Pagination (optional for blog)
paginate: 5
paginate_path: "/blog/page:num/"

# Google Analytics (optional)
google_analytics: UA-XXXXXXXX-X # Replace with your own Tracking ID

# Social media (optional)
twitter_username: johndoe
github_username: johndoe

# Additional settings
highlighter: rouge
show_excerpts: true
